---
configure_dotfiles: false
configure_terminal: false
configure_osx: false

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove:
  - Apps
  - Safari
  - Messages
  - Maps
  - Photos
  - 'FaceTime'
  - Phone
  - Contacts
  - Reminders
  - Notes
  - TV
  - Music
  - Keynote
  - Pages
  - Games
  - 'App Store'
  - 'iPhone Mirroring'
dockitems_persist: []
# - name: "Sublime Text"
#   path: "/Applications/Sublime Text.app/"
#   pos: 5

configure_sudoers: false
sudoers_custom_config: ""

dotfiles_repo: https://github.com/geerlingguy/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Development/GitHub/dotfiles
dotfiles_repo_version: master # Replace with your default branch
dotfiles_files:
  - .zshrc
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc

homebrew_installed_packages:
  - git
  - gh
  - nmap
  - node
  - nvm
  - wget

homebrew_taps: []
homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - docker
  - firefox
  - google-chrome
  - slack
  - visual-studio-code
  - obsidian
  - github
  - figma
  - google-drive
  - keepassxc
  - rectangle
  - timing

mas_installed_apps: []
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

composer_packages: []
gem_packages: []
npm_packages: []
pip_packages: []


# Set to 'true' to configure Sublime Text.
configure_sublime: false
sublime_base_path: "~/Library/Application Support/Sublime Text"
sublime_config_path: "Packages/User"
sublime_package_control:
  - "DocBlockr"
  - "Dockerfile Syntax Highlighting"
  - "FileDiffs"
  - "GitHub Flavored Markdown Preview"
  - "Jinja2"
  - "Package Control"
  - "Pretty JSON"
  - "SublimeLinter"
  - "SublimeLinter-contrib-yamllint"
  - "Theme - Cobalt2"
  - "TrailingSpaces"
  - "WordingStatus"

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
